{% set name = "TTS" %}
{% set version = "0.22.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/TTS-{{ version }}.tar.gz
  sha256: b91119da7ff2ae7b3dae7328edf9af4db3b48c40eb4ce15d11ed8f5ee9bd7086

build:
  number: 0
  skip: true  # [py>=312 or win]
  entry_points:
    - tts=TTS.bin.synthesize:main
    - tts-server = TTS.server.server:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - cython ~=0.29.30
    - numpy >=1.22.0
    - pip
    - python
    - setuptools
    - wheel
    - packaging >=23.1
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - cython ~=0.29.30
    - scipy >=1.11.2
    - pytorch >=2.1
    - torchaudio
    - pysoundfile >=0.12.0
    - librosa >=0.10.0
    - scikit-learn >=1.3.0
    - numba >=0.57.0
    - inflect >=5.6.0
    - tqdm >=4.64.1
    - anyascii
    - coqpit >=0.3.0
    - pyyaml >=6.0
    - fsspec >=2023.6.0
    - aiohttp >=3.8.1
    - packaging >=23.1
    - flask
    - pysbd >=0.3.4
    - umap-learn >=0.5.1
    - pandas >=1.4,<2.0
    - matplotlib-base >=3.7.0
    - coqui-trainer >=0.0.32
    - coqpit >=0.0.16
    - jieba
    - pypinyin
    - hangul_romanize
    - gruut ==2.2.3
    - jamo
    - nltk
    - g2pkk >=0.1.1
    - bangla
    - bnnumerizer
    - bnunicodenormalizer
    - einops >=0.6.0
    - transformers >=4.33.0
    - encodec >=0.1.1
    - gdown
    - unidecode >=1.3.2
    - num2words
    - spacy >=3
    - sudachipy >=0.5.2,!=0.6.1
    - sudachidict-core >=20211220

test:
  imports:
    - TTS
    - TTS.bin
  commands:
    - pip check
    - tts --help
    - tts-server --help
  requires:
    - pip

about:
  home: https://github.com/coqui-ai/TTS
  summary: Deep learning for Text to Speech by Coqui.
  doc_url: https://tts.readthedocs.io/en/latest/
  license: MPL-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
