{% set name = "TTS" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/TTS-{{ version }}.tar.gz
  sha256: ad3aa334fd6c30733ff4d733d51818008f897d1e31d21dcd264cadeb11d43fbd

build:
  number: 0
  skip: true  # [py>=310 or py2k or win]
  entry_points:
    - tts=TTS.bin.synthesize:main
    - tts-server = TTS.server.server:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - anyascii
    - coqpit
    - cython
    - flask
    - fsspec >=2021.04.0
    - gdown
    - gruut ~=2.0.0
    - inflect
    - jieba
    - librosa ==0.8.0
    - matplotlib-base
    - mecab-python3 ==1.0.3
    - numba ==0.53
    - numpy ==1.19.5
    - pandas
    - pypinyin
    - pysbd
    - python
    - pyworld
    - pyyaml
    - scipy >=0.19.0
    - pysoundfile
    - tensorboardx
    - pytorch >=1.7
    - tqdm
    - umap-learn ==0.5.1
    - unidic-lite ==1.0.8
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - TTS
    - TTS.bin
  commands:
    - pip check
    - tts --help
    - tts-server --help
  requires:
    - pip

about:
  home: https://github.com/coqui-ai/TTS
  summary: Deep learning for Text to Speech by Coqui.
  doc_url: https://tts.readthedocs.io/en/latest/
  license: MPL-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
